#!/bin/sh -e

# SPDX-License-Identifier: GPL-2.0

#
# Copyright (C) 2026 Intel Corporation
#

#
# Environment:
#
# KERNEL_SRC			- Directory holding output of Linux kernel
#				  build. If defined, it will be used to install
#				  kernel modules from.
# NVIDIA_SRC			- Directory containing the open-source
# 				  NVIDIA driver source.
#

[ -d "$NVIDIA_SRC" ] && [ -d "$KERNEL_SRC" ] && {
	make -C "$NVIDIA_SRC" SYSSRC="$KERNEL_SRC" INSTALL_MOD_PATH="$1" modules_install || /bin/true
} || {
	echo "Export NVIDIA_SRC in order to install proprietary NVIDIA driver"
}
